name: conv
description: ""
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  image: ^4.5.4
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/ic.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/ic.png
  color_dark: "#000000"
  image_dark: assets/ic.png

  android_12:
    image: assets/ic.png
    color: "#ffffff"
    image_dark: assets/ic.png
    color_dark: "#000000"

  android: true
  ios: false
  web: false
